name: Dendron

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Delete cache if present
              run: "rm -rf .next && rm -rf docs && rm -rf node_modules"

            - name: Install npm dependencies
              run: npm install @dendronhq/dendron-cli@latest

            - name: Output dependency tree to log
              run: cat package*.json

            - name: Export notes
              run: npx dendron publish export --target github --yes

            - name: Deploy site
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: pages
                  publish_dir: docs/
                  force_orphan: true
                  cname: "pkm.dendron.so" # UPDATE WITH DOMAIN NAME
